### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by kllmagn** [alphagruis/alphagruis-eth#1]
Are there any plans for Linux version to be released?

**Comment by alphagruis** [comment]
Hi **kllmagn**, all **alphagruis**'s miners are cross-platform and functionally identical on all platforms except overclocking (fully supported for all AMD and NVIDIA GPUs, including next-generation ones, only on the Windows platform). The official version for the Linux platform will be released shortly. Keep following us. Thank you for your interest.
